# application.properties中的配置会覆盖application.yml中的配置
debug: true
neo:
  title: 纯洁的微笑
  description: 分享技术，品味生活

server:
  port: 8082
  servlet:
    session:
      timeout: 60

logging:
  path: logs
  file: mylog.log

logsbyproduce:
  dir: D:/tmp/logs/p1app_v2
  index: logsbyp1app_v2
  type: p1app_v2
  pool:
    size: 4

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    # 关闭Thymeleaf的缓存，不然在开发过程中修改页面不会立刻生效，需要重启，生产环境配置为true 
    cache: false
  
  security:
    user:
      name: admin # 默认为user
      password: admin123 # 默认随机生成，在控制台输出