# application.properties中的配置会覆盖application.yml中的配置
debug: true
neo:
  title: 纯洁的微笑
  description: 分享技术，品味生活
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    # 关闭Thymeleaf的缓存，不然在开发过程中修改页面不会立刻生效，需要重启，生产环境配置为true 
    cache: false
  
  security:
    user:
      name: admin # 默认为user
      password: admin123 # 默认随机生成，在控制台输出